### ISSUE TITLE
[Bug] Incompatible with ReservedItemSlotCore slots

### ISSUE THREAD

**Issue by Test-Account666** [MasterAli2/TeleportDecline#4]
Hello!

I love the mod :3

I did notice however, that this mod isn't compatible with the slots added by ReservedItemSlotCore.

I still drop those items - Even though I declined the teleport.

Would be nice if that was fixed :)

Thanks in advance!

**Comment by MasterAli2** [comment]
Hi, unfortunately I can't update the mod since I recently moved and stopped making mods in general but for now since you have experience in making mods, I allow you to fork the project and fix this bug for you're own Personal Use if you want)

(I assumed you have experience making mods since you have multiple mods published on your github)

**Comment by Test-Account666** [comment]
Hello!

Thanks for answering :)

I'll see what I can do ^^
